-- The catalogue of things you have at home. `quantity` is a running total kept
-- in step with item_events; the events are the record, this is the answer.
CREATE TABLE items (
    id            UUID PRIMARY KEY,
    user_id       BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name          TEXT          NOT NULL,
    category      TEXT,
    unit          VARCHAR(10)   NOT NULL DEFAULT 'PIECE',
    quantity      NUMERIC(12,3) NOT NULL DEFAULT 0,
    low_threshold NUMERIC(12,3),
    archived      BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- One live "Eggs" per person. Archived rows are excluded so a name can be
-- reused after an item is retired.
CREATE UNIQUE INDEX idx_items_user_name ON items (user_id, lower(name)) WHERE NOT archived;
CREATE INDEX idx_items_user_updated ON items (user_id, updated_at);

-- Append-only. Rows are never updated or deleted, and the id is generated by
-- the client, so replaying a sync is a no-op instead of a duplicate.
CREATE TABLE item_events (
    id             UUID PRIMARY KEY,
    user_id        BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    item_id        UUID          NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    type           VARCHAR(10)   NOT NULL,
    quantity_delta NUMERIC(12,3) NOT NULL,
    unit_price     NUMERIC(10,2),
    note           TEXT,
    occurred_at    TIMESTAMPTZ   NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_item_events_user_created ON item_events (user_id, created_at);
CREATE INDEX idx_item_events_item ON item_events (item_id, occurred_at DESC);
