package com.homestock.item;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(name = "items")
public class Item {

    /** Generated by the client so an item created offline keeps its identity. */
    @Id
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(nullable = false)
    private String name;

    private String category;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Unit unit = Unit.PIECE;

    /** The running total of every event on this item. Never set directly. */
    @Column(nullable = false)
    private BigDecimal quantity = BigDecimal.ZERO;

    /** At or below this, the item shows up on the shopping list. Null = never. */
    @Column(name = "low_threshold")
    private BigDecimal lowThreshold;

    @Column(nullable = false)
    private boolean archived = false;

    @Column(name = "created_at", nullable = false, updatable = false, insertable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt = Instant.now();
}
